### ISSUE TITLE
"Before" example mixed with command on a table misbehaves

### ISSUE THREAD

**Issue by elnur** [concordion/concordion#217] opened 2016-08-19 22:21 UTC
When I combine [executing command on a table](http://concordion.org/instrumenting/java/markdown/#execute-command-on-a-table) with ["before" examples](http://concordion.org/instrumenting/java/markdown/#before-examples), only the last row of the table gets executed for the second example.

I add 5 rows to a database table using command on a table in "before" example. I do that because 2 examples in the specification need the same test data. BTW, I clear the DB before each test.

So, when the first example is being executed, the "before" example adds 5 rows to a database table by looping through the specification table and calling a command that creates a user in the DB. Everything is fine here.

But when the second example is being executed, the "before" example adds only 1 row to a database table because the pointer seems to be stuck on the last row of the specification table.

My assumption is that the whole specification table in "before" example has to loop from start before each "real" example.

**Comment by nigelcharman** [comment] 2016-08-20 01:03
Thanks for reporting it. I've managed to reproduce it.

**Comment by nigelcharman** [comment] 2016-08-20 09:17
@drtimwright keen for your thoughts on this one. The issue is that the "execute on a table" command expects only to be executed once. Specifically it:

1. iterates over the rows, setting commandCall to each row in turn, and leaving it on the last row.
2. it also copies the child command calls from the header to each row. If you work around (1), this causes it to fail.

See [TableStrategy](https://github.com/concordion/concordion/blob/before-example-using-table/src/main/java/org/concordion/internal/command/ExecuteCommand.java#L56).

The same will be true of "execute on a list" and possibly other 3rd party commands.

I see 2 main options:

1. Clone the before example (element and command calls) so that each example has a unique copy of it (and possibly hide the "before example" element in the output HTML)
2. Enforce a new rule that commands may be executed multiple times, and modify "execute on a table" to support this.

The first seems safer if we ever want to support parallel examples. It would also allow us to potentially show the before example for individual examples (eg. to echo some output, display timings or show exceptions). But it's quite a big change.

The second is likely to require less change, but is still non-trivial.

**Comment by drtimwright** [comment] 2016-08-21 05:54
Yeah, the way tables execute is different to other ways.

Can anyone see if my pull request #214 fixes this? I spent some time getting the before bits working for examples embedded in tables in that pull request.

Tim

**Comment by nigelcharman** [comment] 2016-08-21 06:12
No, this still behaves the same way with #214 merged in. But we should probably use #214 as a base for fixing this from.

I'll prioritise reviewing #214 and getting a 2.1.0-SNAPSHOT release of that.

@elnur - looks like this might take a while to fix. As a workaround, you may need to create a separate table for each row in the before example.

**Comment by nigelcharman** [comment] 2016-08-21 06:26
@drtimwright there's also some potential edge cases such as 

- the before example containing a table with multiple examples, 
- or an outer example containing a table with one row marked as the before example

**Comment by elnur** [comment] 2016-08-21 13:00
@nigelcharman, no worries. Copied the "before" table to each example for now. I'll refactor once it's fixed and released.

**Comment by drtimwright** [comment] 2016-08-22 09:55
Having a table in the before example to setup a database is actually a key use-case I imagined when writing the example extension. So it'd be something nice to get working. Will look at it soon. Hopefully.

**Comment by drtimwright** [comment] 2016-08-24 07:39
Hey,

Wrote some code that fixes this problem. Basically I had to:

* Store and remove the initial element in the table command call
* Store and remove the command calls set on each cell in the table as each row is executed.

I'll add it to the pull request for #214 

Tim

**Comment by nigelcharman** [comment] 2017-07-19 07:02
@elnur sorry forgot to close the issue. The fix for this went out with 2.1.0. Please open another issue if there's any problems with it.

**Closed by nigelcharman** 2017-07-19 07:02 UTC
Labels: bug
