### ISSUE TITLE
Using Concordion with Screenshot with examples

### ISSUE THREAD

**Issue by gauravchopra** [concordion/concordion#290] opened 2019-08-19 23:48 UTC
I have written 2 examples in my specification and I am making use of Custom screenshot taker, facing below issues on usage:

Extension can be only set once, selenium driver cannot be quit in after example hook(as this results in No session exception
2)On omitting the after hook, test case uses the screenshot taken in 1st example in 2nd example as well (seems like the driver once set on extension cannot be reinitialise for second example)

**Comment by nigelcharman** [comment] 2019-08-20 10:49
Please would you attach a minimal test case that exhibits the issue

**Comment by nigelcharman** [comment] 2019-09-15 17:02
Closing since no reproducible test case provided

**Closed by nigelcharman** 2019-09-15 17:02 UTC
